<?php
return array(
	'non_smoking_rooms' => 'non smoking rooms / smoking rooms',
    'air_conditioning' => 'air conditioning',
    'bathrobes' => 'towel',
    'daily_newspaper' => 'daily newspaper',
    'desk' => 'desk',
    'hair_dryer' => 'hair dryer',
    'ironing_facilities' => 'ironing facilities',
    'in_room_safe' => 'in room safe',
    'television_LCD/plasma_screen' => 'Flat-screen TV',
    'bathtub' => 'bathtub',
    'shower' => 'shower',
    'mini_bar' => 'mini bar',
    'balcony/terrace' => 'balcony/terrace',
    'satellite/cable_TV' => 'satellite/cable TV',
    'coffee/tea_maker' => 'coffee/tea maker',
    'complimentary_bottled_water' => 'complimentary bottled water',
    'Free_LAN_and_WiFi_access' => 'Free LAN and WiFi access',
    'Telephone'=>'Telephone', 
    'Cable_Chanel'=>'Cable Chanel',
    'sitting_area'=>'Sitting Area', 
    'living_area' => 'living area',
    'dining_area' => 'dining area', 
    'sun_loungers' => 'sun loungers',
    'private_pool' => 'private pool',
    'hard_wood_/_parquet_floor'=>'hard wood / parquet floor', 
    'wardrobe_/_closet'=>'wardrobe/closet', 
    'free_toiletries'=>'free toiletries', 
    'toilet'=>'toilet', 
    'bathroom'=>'bathroom',
    'Wake_up_service'=>'Wake-up service', 
    'linens'=>'linens',
    'wooden_floor' => 'Wooden floor',
    'sofa' => 'Sofa',
);