<?php
return array(
      'tour_desk' => 'Tour desk',
      'gift_shop' => 'Gift shop',
      'parcel_postal' => 'Parcel & postal',
      'steam_bath' => 'Steam bath',
      '24_hours_room_service' => '24-hours room service',
      'airport_transportation' => 'Airport transportation',
      'car_rental' => 'Car rental',
      'Air_ticket_reservation' => 'Air ticket reservation',
      '24_hours_concierge' => '24-hours concierge',
      'turndown_service' => 'Turndown service',
      'laundry' => 'Laundry',
      'fitness_center' => 'fitness center',
      'jacuzzi' => 'Jacuzzi',
      'spa' => 'Spa',
      'games_room' => 'Games room',
      'kids_club' => 'Kids club',
      'squash_courts' => 'Squash courts',
      'garden' => 'Garden',
      'massage' => 'Massage',
      'steamroom' => 'Steamroom',
      'golf_course_(on_site)' => 'Golf course (on site)',
      'outdoor_pool' => 'Outdoor pool',
      'tennis_courts' => 'Tennis courts',
      'golf_course_(within_3_km)' => 'Golf course (within 3 km)',
      'pool_(kids)' => 'Pool (kids)',
      'water_sports_(motorized)' => 'Water sports (motorized)',
      'hot_spring_bath' => 'Hot spring bath',
      'private_beach' => 'Private beach',
      'water_sports_(non_-_motorized)' => 'Water sports (non-motorized)',
      'indoor_pool' => 'Indoor pool',
      'sauna' => 'Sauna'
);